version: 1
type: maven
resolver:
  snapshotRepo: jcenter-remote
  releaseRepo: jcenter-remote
  serverID: orbitera_artifactory
deployer:
  snapshotRepo: libs-snapshot-local
  releaseRepo: libs-snapshot-local
  serverID: orbitera_artifactory